# Site settings
title: myblog
email: dstamen[at]gmail.com
description: > # this means to ignore newlines until "baseurl:"
  a blog about virtualization, messaging and technology.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://davidstamen.com" # the base hostname & protocol for your site
twitter_username: davidstamen
github_username:  dstamen

# Build settings
markdown: kramdown
